import QA_automation_phone as qa
import time
device = qa.get_devices()
connect = qa.connect(device=device[0])
connect.press_home()
# connect.press_back()
# connect.press_call()
connect.press_volume_down()
time.sleep(1)
connect.press_volume_up()
# connect.press_recent()
connect.press_power()
# connect.press_camera()
# connect.press_tab()
# time.sleep(4)
# connect.press_camera_focus()
# connect.press_enter()
# connect.press_del()
# connect.press_media_play_pause()
# connect.press_E()   
# connect.press_space()
# connect.press_media_next()
# time.sleep(1)
# connect.press_media_previous()