import QA_automation_phone as qa
import time
devices = qa.get_devices()
cn = qa.connect(devices[0])
cn.open_setting_reset()
time.sleep(2)
cn.open_setting_reset_network()
time.sleep(2)
cn.open_setting_wifi()
cn.open_setting_bluetooth()
time.sleep(2)
cn.open_setting_display()
time.sleep(2)
cn.open_setting_sound()
# cn.open_setting_storage()
# cn.open_setting_battery()
# cn.open_setting_location()
# cn.open_setting_security()

# cn.open_setting_language()
# cn.open_setting_keyboard()
# cn.open_setting_input()
# cn.open_setting_date_time()
# cn.open_setting_accessibility()
# cn.open_setting_print()
# cn.open_setting_development()
# cn.open_setting_device_info()
# cn.open_setting_about_phone()
# cn.open_account_manager()
# cn.open_setting_app()
# cn.open_add_account()