from QA_automation_phone.setting import *
import time
device = "R58N3012RYE"
# open_setting_reset("R58NC2W4ZQK")
# open_setting_reset_network("R58NC2W4ZQK")
# open_setting_wifi(device)
# open_setting_bluetooth("R58NC2W4ZQK")
# open_setting_display("R58NC2W4ZQK")
# open_setting_sound("R58NC2W4ZQK")
# open_setting_storage("R58NC2W4ZQK")
# open_setting_battery("R58NC2W4ZQK")
# open_setting_location("R58NC2W4ZQK")
# open_setting_security("R58NC2W4ZQK")
# open_setting_account("R58NC2W4ZQK")
# open_setting_language("R58NC2W4ZQK")
# open_setting_keyboard("R58NC2W4ZQK")
# open_setting_input("R58NC2W4ZQK")
# open_setting_date_time("R58NC2W4ZQK")
# open_setting_accessibility("R58NC2W4ZQK")
# open_setting_ime("R58NC2W4ZQK")
# open_setting_print("R58NC2W4ZQK")
# open_setting_development("R58NC2W4ZQK")
# open_setting_device_info("R58NC2W4ZQK")
# open_setting_about_phone("R58NC2W4ZQK")
# open_account_manager("R58NC2W4ZQK")
# open_setting_app("R58NC2W4ZQK")
open_add_account(device)